package com.example.vision_assistant

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.util.Base64
import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugin.common.MethodChannel.MethodCallHandler
import io.flutter.plugin.common.MethodChannel.Result
import kotlinx.coroutines.*
import java.io.File
import java.io.ByteArrayOutputStream

/**
 * MlcLlmPlugin bridges Flutter -> MLC LLM on-device inference.
 *
 * NOTE: ai.mlc:mlc4j is a *local* Gradle subproject generated by `mlc_llm package`
 * and is NOT published to Maven Central. The engine is accessed via reflection so that
 * the APK compiles and installs cleanly from CI. Full inference requires the prebuilt
 * libtvm4j_runtime_packed.so placed in dist/lib/mlc4j at build time.
 */
class MlcLlmPlugin : FlutterPlugin, MethodCallHandler {
    private lateinit var channel: MethodChannel
    private lateinit var context: Context
    private var engineObj: Any? = null
    private val scope = CoroutineScope(Dispatchers.IO + SupervisorJob())

    // reflection helpers
    private fun loadEngineClass(): Class<*>? = try {
        Class.forName("ai.mlc.mlcllm.MLCEngine")
    } catch (_: ClassNotFoundException) { null }

    private fun isRuntimeAvailable(): Boolean = loadEngineClass() != null

    override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        channel = MethodChannel(binding.binaryMessenger, "mlc_llm_channel")
        channel.setMethodCallHandler(this)
        context = binding.applicationContext
    }

    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        channel.setMethodCallHandler(null)
        scope.cancel()
        safeUnload()
    }

    override fun onMethodCall(call: MethodCall, result: Result) {
        when (call.method) {
            "loadModel" -> {
                val modelPath = call.argument<String>("modelPath")
                if (modelPath == null) { result.error("INVALID_ARGUMENT", "modelPath is required", null); return }
                loadModel(modelPath, result)
            }
            "analyzeImage" -> {
                val imageBytes = call.argument<ByteArray>("imageBytes")
                val prompt = call.argument<String>("prompt") ?: "Describe this image"
                if (imageBytes == null) { result.error("INVALID_ARGUMENT", "imageBytes is required", null); return }
                analyzeImage(imageBytes, prompt, result)
            }
            "generateText" -> {
                val prompt = call.argument<String>("prompt")
                if (prompt == null) { result.error("INVALID_ARGUMENT", "prompt is required", null); return }
                generateText(prompt, result)
            }
            "unloadModel"   -> unloadModel(result)
            "isModelLoaded" -> result.success(engineObj != null)
            else            -> result.notImplemented()
        }
    }

    private fun loadModel(modelPath: String, result: Result) {
        scope.launch {
            try {
                if (!isRuntimeAvailable()) {
                    withContext(Dispatchers.Main) {
                        result.error("RUNTIME_UNAVAILABLE",
                            "MLC runtime not bundled in this build. Run `mlc_llm package` and include dist/lib/mlc4j.", null)
                    }
                    return@launch
                }
                val modelDir = File(modelPath)
                if (!modelDir.exists()) {
                    withContext(Dispatchers.Main) {
                        result.error("MODEL_NOT_FOUND", "Model directory not found: $modelPath", null)
                    }
                    return@launch
                }
                val cls = loadEngineClass()!!
                val eng = cls.getDeclaredConstructor().newInstance()
                cls.getMethod("reload", String::class.java).invoke(eng, modelPath)
                engineObj = eng
                withContext(Dispatchers.Main) { result.success(true) }
            } catch (e: Exception) {
                withContext(Dispatchers.Main) { result.error("LOAD_ERROR", "Failed to load model: ${e.message}", null) }
            }
        }
    }

    private fun analyzeImage(imageBytes: ByteArray, prompt: String, result: Result) {
        scope.launch {
            try {
                val eng = engineObj ?: run {
                    withContext(Dispatchers.Main) { result.error("MODEL_NOT_LOADED", "Model not loaded", null) }
                    return@launch
                }
                val bitmap = BitmapFactory.decodeByteArray(imageBytes, 0, imageBytes.size) ?: run {
                    withContext(Dispatchers.Main) { result.error("IMAGE_ERROR", "Failed to decode image", null) }
                    return@launch
                }
                val resized = Bitmap.createScaledBitmap(bitmap, 448, 448, true)
                val stream  = ByteArrayOutputStream()
                resized.compress(Bitmap.CompressFormat.JPEG, 85, stream)
                val imageBase64 = Base64.encodeToString(stream.toByteArray(), Base64.NO_WRAP)
                val text = reflectGenerate(eng, buildVisionPrompt(prompt, imageBase64))
                bitmap.recycle(); resized.recycle()
                withContext(Dispatchers.Main) { result.success(text) }
            } catch (e: Exception) {
                withContext(Dispatchers.Main) { result.error("INFERENCE_ERROR", "Inference failed: ${e.message}", null) }
            }
        }
    }

    private fun generateText(prompt: String, result: Result) {
        scope.launch {
            try {
                val eng = engineObj ?: run {
                    withContext(Dispatchers.Main) { result.error("MODEL_NOT_LOADED", "Model not loaded", null) }
                    return@launch
                }
                val text = reflectGenerate(eng, prompt)
                withContext(Dispatchers.Main) { result.success(text) }
            } catch (e: Exception) {
                withContext(Dispatchers.Main) { result.error("INFERENCE_ERROR", "Generation failed: ${e.message}", null) }
            }
        }
    }

    private fun unloadModel(result: Result) {
        scope.launch {
            try {
                safeUnload()
                withContext(Dispatchers.Main) { result.success(true) }
            } catch (e: Exception) {
                withContext(Dispatchers.Main) { result.error("UNLOAD_ERROR", "Failed to unload: ${e.message}", null) }
            }
        }
    }

    private fun reflectGenerate(eng: Any, prompt: String): String {
        return try {
            val cls      = eng.javaClass
            val chat     = cls.getMethod("getChat").invoke(eng)
            val comps    = chat.javaClass.getMethod("getCompletions").invoke(chat)
            val messages = listOf(mapOf("role" to "user", "content" to prompt))
            val response = comps.javaClass.getMethod(
                "create", List::class.java, Int::class.java, Double::class.java
            ).invoke(comps, messages, 300, 0.3)
            val choices = response.javaClass.getMethod("getChoices").invoke(response) as List<*>
            val choice  = choices.firstOrNull() ?: return "No response generated"
            val message = choice.javaClass.getMethod("getMessage").invoke(choice)
            message.javaClass.getMethod("getContent").invoke(message) as? String ?: "No response generated"
        } catch (e: Exception) {
            "Inference unavailable: ${e.message}"
        }
    }

    private fun safeUnload() {
        try { engineObj?.let { eng -> eng.javaClass.getMethod("unload").invoke(eng) } }
        catch (_: Exception) { } finally { engineObj = null }
    }

    private fun buildVisionPrompt(userPrompt: String, imageBase64: String) =
        "<start_of_turn>user\n<image>$imageBase64</image>\n\n" +
        "You are a vision assistant for visually impaired users. Analyze the image and respond to: $userPrompt\n\n" +
        "Provide clear, helpful descriptions including:\n" +
        "- What is in the scene\n- Object positions (left, right, center, near, far)\n" +
        "- Any obstacles or hazards\n- Text or signs if visible\n- Navigation guidance if relevant\n\n" +
        "Be concise but thorough.<end_of_turn>\n<start_of_turn>model\n"
}
